# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexo187', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMENT', models.CharField(max_length=200)),
                ('IMAGE', models.ImageField(upload_to='')),
                ('CREATED_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPLOADED_DATE', models.DateTimeField(blank=True, null=True)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
