# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexo187', '0002_auto_20180306_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='CREATED_DATE',
        ),
        migrations.AlterField(
            model_name='picture',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
